CREATE SCHEMA IF NOT EXISTS public;

create table flyway_schema_history
(
    installed_rank integer                 not null
        constraint flyway_schema_history_pk
            primary key,
    version        varchar(50),
    description    varchar(200)            not null,
    type           varchar(20)             not null,
    script         varchar(1000)           not null,
    checksum       integer,
    installed_by   varchar(100)            not null,
    installed_on   timestamp default now() not null,
    execution_time integer                 not null,
    success        boolean                 not null
);

alter table flyway_schema_history
    owner to postgres;

create index flyway_schema_history_s_idx
    on flyway_schema_history (success);

create table buyer
(
    id         bigint generated by default as identity
        primary key,
    cpf        varchar(255),
    email      varchar(255),
    first_name varchar(255),
    last_name  varchar(255),
    phone      varchar(255)
);

alter table buyer
    owner to postgres;

create table place
(
    id           bigint generated by default as identity
        primary key,
    city         varchar(255),
    country      varchar(255),
    description  varchar(255),
    max_capacity bigint,
    name         varchar(255),
    number       varchar(255),
    street       varchar(255)
);

alter table place
    owner to postgres;

create table event
(
    id           bigint generated by default as identity
        primary key,
    category     varchar(255),
    description  varchar(255),
    max_capacity bigint not null,
    name         varchar(255),
    place_id     bigint
        constraint ukcb9u5sic6cixnle1m1xmnncgj
            unique
        constraint fkpuvix4lexrakgdlt8si1tbtxv
            references place
);

alter table event
    owner to postgres;

create table event_dates
(
    event_id bigint not null
        constraint fkpvpgjqmelgstviirtooq3mw2t
            references event,
    dates    timestamp(6)
);

alter table event_dates
    owner to postgres;

create table purchase
(
    id            bigint generated by default as identity
        primary key,
    purchase_date date,
    buyer_id      bigint
        constraint ukmw2t8o24ll0fm6y2jquxeuv61
            unique
        constraint fkb8m8lunr6ml5pv1vlurpldl9k
            references buyer
);

alter table purchase
    owner to postgres;

create table ticket_field
(
    id    bigint generated by default as identity
        primary key,
    name  varchar(255),
    value varchar(255)
);

alter table ticket_field
    owner to postgres;

create table ticket_type
(
    id       bigint generated by default as identity
        primary key,
    name     varchar(255),
    price    double precision not null,
    quantity bigint           not null
);

alter table ticket_type
    owner to postgres;

create table event_tickets_distribution
(
    event_id                 bigint not null
        constraint fkt0e957fball4bff9iwxr86npx
            references event,
    type_value               bigint,
    tickets_distribution_key bigint not null
        constraint fkgjm3g6wbqeqht7phm14wvgpw9
            references ticket_type,
    primary key (event_id, tickets_distribution_key)
);

alter table event_tickets_distribution
    owner to postgres;

create table ticket
(
    id             bigint generated by default as identity
        primary key,
    event_id       bigint
        constraint ukgya3vr762793uoto348c2oqbi
            unique
        constraint fkfytuhjopeamxbt1cpudy92x5n
            references event,
    ticket_type_id bigint
        constraint ukt1h4mqd5p4gykoqss46klo1b5
            unique
        constraint fkicdt7jp8dniw1fw6y8y0u9gcr
            references ticket_type,
    user_id        bigint
        constraint uki0i7rws9vvh121bg8mibj73pe
            unique
        constraint fkkldyapqgmnrloi6gkbcqiwdik
            references buyer
);

alter table ticket
    owner to postgres;

create table purchase_ticket
(
    purchase_id bigint not null
        constraint fkilpfm45l53eyf5klevpg2p7q1
            references purchase,
    ticket_id   bigint not null
        constraint ukmevm6e9tnhr548n2na2a0e3w2
            unique
        constraint fkg1scbgahrl95j0u8b35a2w5t8
            references ticket
);

alter table purchase_ticket
    owner to postgres;

create table ticket_dates
(
    ticket_id bigint not null
        constraint fksefvyrkxcpqlgabykxq2e4o7o
            references ticket,
    dates     date
);

alter table ticket_dates
    owner to postgres;

create table ticket_type_fields
(
    ticket_type_id bigint not null
        constraint fkht2lxysgowh9114u2dmbil7ir
            references ticket_type,
    fields_id      bigint not null
        constraint ukfeximps3f862qa8bdnfsjuf52
            unique
        constraint fkosa2ia29peaf7ysysb5cosf1q
            references ticket_field
);

alter table ticket_type_fields
    owner to postgres;



